"use client";

import React, { useState } from "react";
import { VerdictStamp } from "../ui/VerdictStamp";
import { useSound } from "@/context/SoundContext";
import { Flame, ShieldAlert, Sparkles, Zap, Award, ThumbsUp, Share2, ArrowRight } from "lucide-react";

const sampleVerdicts = [
  {
    title: "CERTIFIED NPC",
    variant: "crimson" as const,
    rotate: "-rotate-4",
    category: "💬 Bio Check",
    auraScore: -450,
    delusion: 88,
    redFlags: 3,
    cringeScore: 92,
    caseNo: "CASE #0812",
    summary:
      "Uses 'Live, Laugh, Love' unironically in 2026. Profile picture taken with default iPhone portrait mode in front of a brick wall.",
    judgeNote:
      "Court decree: Subject is 99.2% background character. High risk of repeating NPC dialog options when spoken to.",
    tags: ["Basic Vibe", "Brick Wall PFP", "Zero Spice"],
  },
  {
    title: "WALKING RED FLAG",
    variant: "crimson" as const,
    rotate: "rotate-3",
    category: "💘 Dating Profile",
    auraScore: -999,
    delusion: 99,
    redFlags: 14,
    cringeScore: 95,
    caseNo: "CASE #0441",
    summary:
      "'If you can't handle me at my worst, you don't deserve me at my best' written right above 'No drama please'.",
    judgeNote:
      "Court decree: Immediate restraining order from all dating apps. Aura is depleted beyond emergency recovery.",
    tags: ["Toxic Energy", "Drama Magnet", "Gaslight King"],
  },
  {
    title: "AURA MERCHANT",
    variant: "gold" as const,
    rotate: "-rotate-2",
    category: "👕 Outfit Check",
    auraScore: 850,
    delusion: 15,
    redFlags: 0,
    cringeScore: 8,
    caseNo: "CASE #0994",
    summary:
      "Thrifted 1990s leather jacket combined with vintage boots and zero effort. Radiating pure villain origin aura.",
    judgeNote:
      "Court decree: High aura detected. Subject permitted to walk slowly while dark synthwave music plays.",
    tags: ["Pure Drip", "Main Character", "Aura Overdrive"],
  },
  {
    title: "MAXIMUM SENTENCE",
    variant: "crimson" as const,
    rotate: "rotate-4",
    category: "🧠 Life Choice",
    auraScore: -1200,
    delusion: 100,
    redFlags: 20,
    cringeScore: 99,
    caseNo: "CASE #0102",
    summary:
      "Texted their ex 'I saw a dog today and thought of you' at 4:15 AM on a Tuesday after 8 months of silence.",
    judgeNote:
      "Court decree: The jury wept. Phone confiscated indefinitely by order of the Supreme AI Bench.",
    tags: ["Late Night Downfall", "Ex Text Disaster", "No Recovery"],
  },
];

export function SampleVerdicts() {
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const { playPaperRustle } = useSound();

  const handleShare = (caseNo: string) => {
    setCopiedId(caseNo);
    playPaperRustle();
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <section className="py-24 bg-[#1A0B08] relative border-t-2 border-[#D4AF37]/40 bg-court-grid">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16 space-y-3">
          <span className="text-xs font-typewriter font-bold tracking-widest text-[#F5D77F] uppercase px-3 py-1 bg-[#2A120D] rounded-full border border-[#D4AF37] shadow">
            EVIDENCE GALLERY ARCHIVE
          </span>
          <h2 className="text-3xl sm:text-5xl font-serif font-black uppercase text-[#F7F2E7] tracking-tight">
            SAMPLE <span className="text-[#D4AF37]">COURT DECREES</span>
          </h2>
          <p className="text-[#C4B69C] text-base sm:text-lg font-serif">
            Official court records generated by our AI Bench. Here is what your trial verdict looks like.
          </p>
        </div>

        {/* Verdict Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {sampleVerdicts.map((item) => (
            <div
              key={item.caseNo}
              className="relative dossier-folder rounded-2xl p-6 sm:p-8 space-y-6 transition-all duration-300 hover:-translate-y-1 shadow-2xl overflow-hidden group border border-[#E2D3B5]"
            >
              {/* Header */}
              <div className="flex items-center justify-between border-b border-[#D8C497] pb-4">
                <div className="flex items-center gap-2 font-typewriter text-xs text-[#5C5245] font-bold">
                  <span className="text-[#991B1B] font-bold">{item.caseNo}</span>
                  <span>•</span>
                  <span>{item.category}</span>
                </div>
                <button
                  onClick={() => handleShare(item.caseNo)}
                  className="text-xs font-typewriter text-[#2C261E] hover:text-[#991B1B] flex items-center gap-1.5 px-3 py-1 rounded bg-[#E5D4AB] border border-[#C8B587] font-bold cursor-pointer"
                >
                  <Share2 className="w-3.5 h-3.5" />
                  {copiedId === item.caseNo ? "COPIED TO WRIT!" : "SHARE DOCKET"}
                </button>
              </div>

              {/* Title & Rubber Stamp */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                  <h3 className="text-2xl font-serif font-black text-[#2C261E] uppercase tracking-tight">
                    {item.title}
                  </h3>
                  <div className="flex items-center gap-2 mt-1 font-typewriter">
                    <span className="text-xs text-[#5C5245] font-bold">AURA SCORE:</span>
                    <span
                      className={`text-sm font-black ${
                        item.auraScore > 0 ? "text-[#997A15]" : "text-[#991B1B]"
                      }`}
                    >
                      {item.auraScore > 0 ? `+${item.auraScore}` : item.auraScore} PTS
                    </span>
                  </div>
                </div>

                <div>
                  <VerdictStamp
                    text={item.title}
                    variant={item.variant}
                    rotate={item.rotate}
                    size="sm"
                  />
                </div>
              </div>

              {/* Summary */}
              <div className="ruled-paper rounded-xl p-4 border border-[#E2D3B5]">
                <p className="text-sm font-typewriter text-[#2C261E] leading-relaxed font-medium">
                  &ldquo;{item.summary}&rdquo;
                </p>
              </div>

              {/* Metric Breakdown Bars */}
              <div className="space-y-2 font-typewriter text-xs">
                <div>
                  <div className="flex justify-between text-[#5C5245] font-bold mb-1">
                    <span>DELUSION LEDGER</span>
                    <span className="text-[#991B1B]">{item.delusion}%</span>
                  </div>
                  <div className="w-full h-2 rounded-full bg-[#EDE2CE] overflow-hidden border border-[#D8C497]">
                    <div
                      className="h-full bg-[#991B1B] rounded-full"
                      style={{ width: `${item.delusion}%` }}
                    />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-[#5C5245] font-bold mb-1">
                    <span>CRINGE COEFFICIENT</span>
                    <span className="text-[#997A15]">{item.cringeScore}%</span>
                  </div>
                  <div className="w-full h-2 rounded-full bg-[#EDE2CE] overflow-hidden border border-[#D8C497]">
                    <div
                      className="h-full bg-[#D4AF37] rounded-full"
                      style={{ width: `${item.cringeScore}%` }}
                    />
                  </div>
                </div>
              </div>

              {/* Judge Note */}
              <div className="pt-2 border-t border-[#D8C497] text-xs font-typewriter text-[#5C5245] italic flex items-start gap-2">
                <span className="text-[#991B1B] font-bold not-italic">BENCH RULING:</span>
                <span>{item.judgeNote}</span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
