"use client";

import React, { useState } from "react";
import { VerdictStamp } from "../ui/VerdictStamp";
import { Flame, ShieldAlert, Sparkles, Zap, Award, ThumbsUp, Share2, ArrowRight } from "lucide-react";

const sampleVerdicts = [
  {
    title: "CERTIFIED NPC",
    variant: "guilty" as const,
    rotate: "-rotate-4",
    category: "💬 Bio Check",
    auraScore: -450,
    delusion: 88,
    redFlags: 3,
    cringeScore: 92,
    caseNo: "CASE #0812",
    summary:
      "Uses 'Live, Laugh, Love' unironically in 2026. Profile picture taken with default iPhone portrait mode in front of a brick wall.",
    judgeNote:
      "Court ruling: Subject is 99.2% background character. High risk of repeating NPC dialog options when spoken to.",
    tags: ["Basic Vibe", "Brick Wall PFP", "Zero Spice"],
  },
  {
    title: "WALKING RED FLAG",
    variant: "guilty" as const,
    rotate: "rotate-3",
    category: "💘 Dating Profile",
    auraScore: -999,
    delusion: 99,
    redFlags: 14,
    cringeScore: 95,
    caseNo: "CASE #0441",
    summary:
      "'If you can't handle me at my worst, you don't deserve me at my best' written right above 'No drama please'.",
    judgeNote:
      "Court ruling: Immediate restraining order from all dating apps. Aura is depleted beyond emergency recovery.",
    tags: ["Toxic Energy", "Drama Magnet", "Gaslight King"],
  },
  {
    title: "AURA MERCHANT",
    variant: "gold" as const,
    rotate: "-rotate-2",
    category: "👕 Outfit Check",
    auraScore: 850,
    delusion: 15,
    redFlags: 0,
    cringeScore: 8,
    caseNo: "CASE #0994",
    summary:
      "Thrifted 1990s leather jacket combined with vintage boots and zero effort. Radiating pure villain origin aura.",
    judgeNote:
      "Court ruling: High aura detected. Subject permitted to walk slowly while dark synthwave music plays.",
    tags: ["Pure Drip", "Main Character", "Aura Overdrive"],
  },
  {
    title: "BEYOND SAVING",
    variant: "guilty" as const,
    rotate: "rotate-4",
    category: "🧠 Life Choice",
    auraScore: -1200,
    delusion: 100,
    redFlags: 20,
    cringeScore: 99,
    caseNo: "CASE #0102",
    summary:
      "Texted their ex 'I saw a dog today and thought of you' at 4:15 AM on a Tuesday after 8 months of silence.",
    judgeNote:
      "Court ruling: The jury wept. Phone confiscated indefinitely by order of the Supreme AI Bench.",
    tags: ["Late Night Downfall", "Ex Text Disaster", "No Recovery"],
  },
];

export function SampleVerdicts() {
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const handleShare = (caseNo: string) => {
    setCopiedId(caseNo);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <section className="py-24 bg-zinc-950 relative border-t border-zinc-800/80">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16 space-y-3">
          <span className="text-xs font-mono font-bold tracking-widest text-red-500 uppercase px-3 py-1 bg-red-950/60 rounded-full border border-red-800/60">
            EVIDENCE GALLERY
          </span>
          <h2 className="text-3xl sm:text-5xl font-black uppercase text-white tracking-tighter">
            SAMPLE <span className="text-red-600">VERDICTS</span>
          </h2>
          <p className="text-zinc-400 text-base sm:text-lg">
            Real court records generated by our AI Jury. Here is what your future holds.
          </p>
        </div>

        {/* Verdict Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {sampleVerdicts.map((item) => (
            <div
              key={item.caseNo}
              className="relative bg-zinc-900/70 border-2 border-zinc-800 hover:border-red-600/70 rounded-2xl p-6 sm:p-8 space-y-6 transition-all duration-300 hover:-translate-y-1 shadow-2xl overflow-hidden group"
            >
              {/* Header */}
              <div className="flex items-center justify-between border-b border-zinc-800 pb-4">
                <div className="flex items-center gap-2 font-mono text-xs text-zinc-400">
                  <span className="text-red-500 font-bold">{item.caseNo}</span>
                  <span>•</span>
                  <span>{item.category}</span>
                </div>
                <button
                  onClick={() => handleShare(item.caseNo)}
                  className="text-xs font-mono text-zinc-400 hover:text-white flex items-center gap-1.5 px-2.5 py-1 rounded bg-zinc-950 border border-zinc-800"
                >
                  <Share2 className="w-3.5 h-3.5" />
                  {copiedId === item.caseNo ? "COPIED!" : "SHARE"}
                </button>
              </div>

              {/* Title & Rubber Stamp */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                  <h3 className="text-2xl font-black text-white uppercase tracking-tight">
                    {item.title}
                  </h3>
                  <div className="flex items-center gap-2 mt-1">
                    <span className="text-xs font-mono text-zinc-400">AURA SCORE:</span>
                    <span
                      className={`text-sm font-mono font-black ${
                        item.auraScore > 0 ? "text-amber-400" : "text-red-500"
                      }`}
                    >
                      {item.auraScore > 0 ? `+${item.auraScore}` : item.auraScore}
                    </span>
                  </div>
                </div>

                <div>
                  <VerdictStamp
                    text={item.title}
                    variant={item.variant}
                    rotate={item.rotate}
                    size="sm"
                  />
                </div>
              </div>

              {/* Summary */}
              <div className="bg-zinc-950/80 rounded-xl p-4 border border-zinc-800/80">
                <p className="text-sm text-zinc-300 leading-relaxed font-medium">
                  &ldquo;{item.summary}&rdquo;
                </p>
              </div>

              {/* Metric Breakdown Bars */}
              <div className="space-y-2 font-mono text-xs">
                <div>
                  <div className="flex justify-between text-zinc-400 mb-1">
                    <span>DELUSION LEVEL</span>
                    <span className="text-red-400 font-bold">{item.delusion}%</span>
                  </div>
                  <div className="w-full h-2 rounded-full bg-zinc-950 overflow-hidden border border-zinc-800">
                    <div
                      className="h-full bg-gradient-to-r from-red-700 to-red-500 rounded-full"
                      style={{ width: `${item.delusion}%` }}
                    />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-zinc-400 mb-1">
                    <span>CRINGE COEFFICIENT</span>
                    <span className="text-amber-400 font-bold">{item.cringeScore}%</span>
                  </div>
                  <div className="w-full h-2 rounded-full bg-zinc-950 overflow-hidden border border-zinc-800">
                    <div
                      className="h-full bg-gradient-to-r from-amber-600 to-amber-400 rounded-full"
                      style={{ width: `${item.cringeScore}%` }}
                    />
                  </div>
                </div>
              </div>

              {/* Judge Note */}
              <div className="pt-2 border-t border-zinc-800/60 text-xs text-zinc-400 font-mono italic flex items-start gap-2">
                <span className="text-red-500 font-bold not-italic">JUDGE:</span>
                <span>{item.judgeNote}</span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
